### ISSUE TITLE
Look at syncing DB from android to Parse

### ISSUE THREAD

**Issue by david-shao** [Fomono/prototype#10]

**Comment by msaranu** [comment]
Saving or Updating Objects

Let's suppose we wanted to save a TodoItem to the Parse database, create a new TodoItem, set the data attributes and then trigger a save with saveInBackground:

TodoItem todoItem = new TodoItem("Do laundry");
// Set the current user, assuming a user is signed in
todoItem.setOwner(ParseUser.getCurrentUser());
// Immediately save the data asynchronously
todoItem.saveInBackground();
// or for a more robust offline save
// todoItem.saveEventually();
Note that there are two ways to save an object: saveInBackground which executes immediately and saveEventually which will store the update on the device and push to the server once internet access is available.

Saving Objects: http://parseplatform.org/docs/android/guide/#saving-objects
